name: 심성보 테스트

# Event: 실행되는 시점을 설정
on:
  push:
    branches:
      - main

jobs:
  worklfows-branch-test:
    runs-on: ubuntu-latest

    steps:
      - name: 'hello world'
        run: echo  "hello world"
